linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: false

  DuplicateProperty:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  IdSelector:
    enabled: false

  Indentation:
    enabled: true
    width: 2

  ImportantRule:
    enabled: false

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  NestingDepth:
    max_depth: 11

  QualifyingElement:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: true
    order:
      - accelerator
      - align-content
      - align-items
      - azimuth
      - background
      - background-attachment
      - background-color
      - background-clip
      - background-image
      - background-position
      - background-position-x
      - background-position-y
      - background-repeat
      - background-size
      - behavior
      - border
      - border-bottom
      - border-bottom-color
      - border-bottom-style
      - border-bottom-width
      - border-collapse
      - border-color
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-radius
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-spacing
      - border-style
      - border-top
      - border-top-color
      - border-top-style
      - border-top-width
      - border-width
      - bottom
      - box-shadow
      - caption-side
      - clear
      - clip
      - color
      - content
      - counter-increment
      - counter-reset
      - cue
      - cue-after
      - cue-before
      - cursor
      - direction
      - display
      - elevation
      - empty-cells
      - fill
      - filter
      - flex
      - flex-basis
      - flex-grow
      - flex-shrink
      - float
      - font
      - font-family
      - font-size
      - font-size-adjust
      - font-stretch
      - font-style
      - font-variant
      - font-weight
      - height
      - ime-mode
      - include-source
      - justify-content
      - layer-background-color
      - layer-background-image
      - layout-flow
      - layout-grid
      - layout-grid-char
      - layout-grid-char-spacing
      - layout-grid-line
      - layout-grid-mode
      - layout-grid-type
      - left
      - letter-spacing
      - line-break
      - line-height
      - list-style
      - list-style-image
      - list-style-position
      - list-style-type
      - margin
      - margin-bottom
      - margin-left
      - margin-right
      - margin-top
      - marker-offset
      - marks
      - max-height
      - max-width
      - min-height
      - min-width
      - opacity
      - orphans
      - outline
      - outline-color
      - outline-style
      - outline-width
      - overflow
      - overflow-x
      - overflow-y
      - padding
      - padding-bottom
      - padding-left
      - padding-right
      - padding-top
      - page
      - page-break-after
      - page-break-before
      - page-break-inside
      - pause
      - pause-after
      - pause-before
      - pitch
      - pitch-range
      - play-during
      - pointer-events
      - position
      - quotes
      - richness
      - right
      - ruby-align
      - ruby-overhang
      - ruby-position
      - scrollbar-arrow-color
      - scrollbar-base-color
      - scrollbar-dark-shadow-color
      - scrollbar-face-color
      - scrollbar-highlight-color
      - scrollbar-shadow-color
      - scrollbar-3d-light-color
      - scrollbar-track-color
      - size
      - speak
      - speak-header
      - speak-numeral
      - speak-punctuation
      - speech-rate
      - stress
      - stroke
      - table-layout
      - text-anchor
      - text-align
      - text-align-last
      - text-decoration
      - text-indent
      - text-justify
      - text-overflow
      - text-shadow
      - text-transform
      - text-autospace
      - text-kashida-space
      - text-underline-position
      - top
      - transition-duration
      - transition-property
      - unicode-bidi
      - vertical-align
      - visibility
      - voice-family
      - volume
      - white-space
      - widows
      - width
      - will-change
      - word-break
      - word-spacing
      - word-wrap
      - writing-mode
      - z-index
      - zoom

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 10

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: false

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: false

  VendorPrefix:
    enabled: false

  ZeroUnit:
    enabled: true

  Compass:
    enabled: false
