const configs = {
  'Alex': { rate: 1 },
  'Alice': {},
  'Alva': {},
  'Amelie': {},
  'Anna': {},
  'Carmit': {},
  'Damayanti': {},
  'Daniel': {},
  'Diego': {},
  'Ellen': {},
  'Fiona': {},
  'Fred': {},
  'Ioana': {},
  'Joana': {},
  'Jorge': {},
  'Juan': {},
  'Kanya': {},
  'Karen': {},
  'Kyoko': {},
  'Laura': {},
  'Lekha': {},
  'Luca': {},
  'Luciana': {},
  'Maged': {},
  'Mariska': {},
  'Mei-Jia': {},
  'Melina': {},
  'Milena': {},
  'Moira': {},
  'Monica': {},
  'Nora': {},
  'Paulina': {},
  'Samantha': {},
  'Sara': {},
  'Satu': {},
  'Sin-ji': {},
  'Tessa': {},
  'Thomas': {},
  'Ting-Ting': {},
  'Veena': {},
  'Victoria': {},
  'Xander': {},
  'Yelda': {},
  'Yuna': {},
  'Yuri': {},
  'Zosia': {},
  'Zuzana': {},
  'Google Deutsch': {},
  'Google US English': {},
  'Google UK English Female': {},
  'Google UK English Male': {},
  'Google español': {},
  'Google español de Estados Unidos': {},
  'Google français': {},
  'Google हिन्दी': {},
  'Google Bahasa Indonesia': {},
  'Google italiano': {},
  'Google 日本語': {},
  'Google 한국의': {},
  'Google Nederlands': {},
  'Google polski': {},
  'Google português do Brasil': {},
  'Google русский': {},
  'Google 普通话（中国大陆': {},
  'Google 粤語（香港）': {},
  'Google 國語（臺灣）': {}
};

export default configs;
