import $ from './core';
import './attributes/attr';
import './attributes/val';
import './css/classes';
import './css/css';
import './css/dimensions';
import './css/position';
import './css/scroll';
import './css/showHide';
import './data/data';
import './events/events';
import './events/ready';
import './manipulation/append';
import './manipulation/beforeAfter';
import './manipulation/clone';
import './manipulation/detach';
import './manipulation/empty';
import './manipulation/html';
import './manipulation/prepend';
import './manipulation/text';
import './manipulation/wrap';
import './traversing/ancestors';
import './traversing/descendants';
import './traversing/position';
import './traversing/traversing';
import './utils/chain';
import './utils/utils';

export default $;
