import $ from './core';
import './ajax/ajax';
import './attributes/attr';
import './attributes/val';
import './core/chain';
import './core/regexp';
import './core/utils';
import './css/classes';
import './css/css';
import './css/dimensions';
import './css/position';
import './css/scroll';
import './css/showHide';
import './data/data';
import './events/events';
import './events/ready';
import './manipulation/append';
import './manipulation/beforeAfter';
import './manipulation/clone';
import './manipulation/detach';
import './manipulation/empty';
import './manipulation/html';
import './manipulation/prepend';
import './manipulation/text';
import './manipulation/wrap';
import './support/browser';
import './support/device';
import './support/feature';
import './support/os';
import './traversing/ancestors';
import './traversing/descendants';
import './traversing/position';
import './traversing/traversing';

export default $;
